### PR TITLE
Add test generator support

### PR DESCRIPTION
**Pull request by teddyzeenny**
**Do not merge - depends on a custom broccoli-lint-eslint branch**

----
Depends on https://github.com/jonathanKingston/broccoli-lint-eslint/pull/2

I added an empty test generator because I'm not sure if you'd like to pick a default testing framework (which should probably be qunit since it is ember-cli's default).

Here is my test generator. I will happily add it to this PR if you' d like.
```javascript
var app = new EmberApp({
  eslint: {
    testGenerator: eslintTestGenerator
  }
});

function eslintTestGenerator(relativePath, errors) {
  var pass = !errors || errors.length === 0;
  return "module('ESLINT - " + path.dirname(relativePath) + "');\n" +
    "test('" + relativePath + " should pass eslint', function() {\n" +
    "  ok(" + pass + ", '" + relativePath + " should pass eslint." + 
    errors.map(function(item) { return item.message; }).join('\n') + "');\n" +
   "});\n";
}
```

### CODE REVIEW

**Comment by jonathanKingston** [comment]
@teddyzeenny I would leave the test generators to the README perhaps, personally I use mocha so we could provide both there.

**Comment by teddyzeenny** [comment]
I added a test generator example for each testing framework to the README.

**Comment by jonathanKingston** [comment]
I'm still testing however the following issues exist:
- [ ] missing path import from example (Might be easier to include all three imports):
```
var path = require('path');
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var jsStringEscape = require('js-string-escape');
```
- [ ] Make example use 'ESLint' as the casing, this matches 'JSHint' and is also the convention
- [ ] The testGenerator line needs changing to: `testGenerator: eslintTestGenerator`

All trivial points, I just want to make sure the barrier to entry is very low.

Thanks again and :+1: for using assert in the mocha test.

**Comment by teddyzeenny** [comment]
Updated.

**Comment by jonathanKingston** [comment]
@teddyzeenny happy to merge with the newly published 0.1.1 broccoli-lint-eslint

**Comment by teddyzeenny** [comment]
Updated the dependency. Thanks for taking the time to review.

**Comment by jonathanKingston** [comment]
:+1:  merged and released. Thanks again.

**Pull request merged**
