### PR TITLE
Bump the version dependency for broccoli-lint-eslint.

### LINKED ISSUE #38: Version bump in broccoli-lint-eslint breaking apps
There's a currently know problem https://github.com/eslint/eslint/issues/5476 bumping the eslint version to 2.3.0 is breaking our apps that use babel-eslint as a parser, I tried to fork these repos and fix the version to 2.2.0 while a fix is published but I failed miserably. Any pointers would be much appreciated.

### PR DESCRIPTION
**Pull request by chriskrycho**
This *should* (and in my local testing *does*) resolve the problem with tokenization from broccoli-lint-eslint using ES6 features, and so resolves #38.

### CODE REVIEW

**Comment by chriskrycho** [comment]
See updated description: with inclusion of `babel-eslint` at its latest beta, this now resolves the estraverse-fb dependency problem.

**Comment by morhook** [comment]
I think that this PR is failing on travis because it depends on https://github.com/jonathanKingston/eslint-config-ember/pull/7

**Comment by chriskrycho** [comment]
That's correct. As soon as he merges that (or adds me as a collaborator on it so I can), this and a whole chain of other things which have this as a dependency should come unblocked.

**Comment by BrianSipple** [comment]
@morhook Yep, same story for https://github.com/jonathanKingston/ember-cli-eslint/pull/40

@jonathanKingston I'd be more than willing to become a collaborator on any of these related repos as well (eslint-config-ember, ember-cli-eslint, broccoli-lint-eslint, eslint-config-nightmare-mode).

**Comment by BrianSipple** [comment]
I'm going to close this, because https://github.com/jonathanKingston/ember-cli-eslint/pull/40/files actually ended up including the same changes (even though I indicated that it was meant to _coincide_ with this PR :smiley:).

Thanks for giving me the head start, though, @chriskrycho!

**Comment by chriskrycho** [comment]
I'm all in favor. 1 PR is better than 2!

**Pull request closed without merging**
